# Site
name: "Subtext 2 Healthcare"
title: "Subtext 2 Healthcare"
description: "Healthcare professional, Data Science Enthusiast."
logo: 'assets/images/pharma_logo.png'
medium: https://medium.com/@subtext2healthcare
twitter: https://twitter.com/subtxt2health
github: https://github.com/subtext2healthcare
favicon: 'assets/images/favicon.png'
google_analytics: 'UA-173359476-1'
disqus: 'Subtext2Healthcare'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/


# Authors
authors:
  Ae Ge:
    name: Ae Ge
    display_name: Ae Ge
    avatar: 'assets/images/pharma_logo.png' 
    email: ag99@protonmail.com
    web: https://subtext2healthcare.github.io/
    
    description: "Healthcare Professional with extensive experience with over 16 years in various roles in the industry – Major concentration: Pharmaceuticals, Biotechnology & Medical Devices. You are currently previewing my website showcasing the projects during my progress in Data Science area."
  
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
